jobs:
  - template: ci/job.build.yml

  - template: ci/job.test.unit.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04

  - template: ci/job.test.unit.yml
    parameters:
      name: MacOSX
      vmImage: macos-10.13

  - template: ci/job.test.unit.yml
    parameters:
      name: Windows
      vmImage: vs2017-win2016

  - template: ci/job.test.acceptance.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04

  - template: ci/job.test.acceptance.yml
    parameters:
      name: MacOSX
      vmImage: macos-10.13

  - template: ci/job.test.acceptance.yml
    parameters:
      name: Windows
      vmImage: vs2017-win2016

  - template: ci/job.combine.yml

trigger:
  - master

pr:
  - master
