#!/usr/bin/env bash
echo "CONDA_PREFIX is $CONDA_PREFIX"

if [ "${NB_UID}not-on-binder" = "not-on-binder" ]; then
  echo "...and that's fine"
else
  if [ "${CONDA_PREFIX}no-conda-prefix" = "no-conda-prefix" ]; then
    echo "...and we set it to ${CONDA_DIR}"
    export CONDA_PREFIX=$CONDA_DIR
  else
    echo "...and that's fine"
  fi
fi

set -ex
python -m pip install -e . --ignore-installed --no-dependencies
jupyter kernelspec install --name robotframework --sys-prefix src/irobotframework/resources
jlpm bootstrap
