parameters:
  name: Linux
  vmImage: ubuntu-16.04

jobs:
  - job: Acceptance_${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn:
      - Build_JS
      - Build_Py
    strategy:
      matrix:
        Firefox:
          PY_VERSION: "36"
          PY_SPEC: ">=3.6,<3.7"
          TEST_KIND: acceptance
          BROWSER: headlessfirefox
        Chrome:
          PY_VERSION: "37"
          PY_SPEC: ">=3.7,<3.8"
          TEST_KIND: acceptance
          BROWSER: headlesschrome
    steps:
      - template: steps.conda.test.yml
        parameters:
          name: ${{ parameters.name }}

      - template: steps.platform.yml
        parameters:
          name: ${{ parameters.name }}

      - template: steps.test.yml
        parameters:
          name: ${{ parameters.name }}
