parameters:
  name: Linux
  vmImage: ubuntu-16.04

jobs:
  - job: Unit_${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn:
      - Build_Py
    strategy:
      matrix:
        Unit_36:
          PY_VERSION: "36"
          PY_SPEC: ">=3.6,<3.7"
          TEST_KIND: unit
        Unit_37:
          PY_VERSION: "37"
          PY_SPEC: ">=3.7,<3.8"
          TEST_KIND: unit
    steps:
      - template: steps.conda.test.yml
        parameters:
          name: ${{ parameters.name }}

      - template: steps.platform.yml
        parameters:
          name: ${{ parameters.name }}

      - template: steps.test.yml
        parameters:
          name: ${{ parameters.name }}
